#!/bin/bash
###define PBS arguments
#PBS -N TajimaD
#PBS -l nodes=1:ppn=10,walltime=30:00:00:00
#PBS -q low
#PBS -j oe
#PBS -o log_TajimaD

###job starting reminder
echo $USER
echo "Starting job at:"
date -d +20minute +'%Y-%m-%d %H:%M:%S'


###job dir
cd $PBS_O_WORKDIR

source activate /public/home/huangyj/anaconda3/envs/python2pop
###variable
#gzvcf
#keep_pop
#prefix
###job command

vcftools --gzvcf $gzvcf --TajimaD 100000 --keep $keep_pop --out ${prefix}.100k
vcftools --gzvcf $gzvcf --TajimaD 50000 --keep $keep_pop --out ${prefix}.50k
vcftools --gzvcf $gzvcf --TajimaD 20000 --keep $keep_pop --out ${prefix}.20k

conda deactivate
###job finished reminder
echo "Finish at:"
date -d +20minute +'%Y-%m-%d %H:%M:%S'
