#!/bin/bash
###define PBS arguments

#PBS -N SNPeff
#PBS -l nodes=1:ppn=20,walltime=30:00:00:00,mem=180g
#PBS -q low
#PBS -j oe
#PBS -o log_vcf_filted

###job starting reminder
echo $USER
echo "Starting job at:"
date -d +20minute +'%Y-%m-%d %H:%M:%S'
set +u -e

###job dir
cd $PBS_O_WORKDIR
###variable
gatk_java='/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.262.b10-1.el7.x86_64/jre/bin/java'
build_dict_script="/public/home/huangyj/anaconda3/envs/population/share/picard-2.18.23-0/picard.jar"
gatk4='/public/home/huangyj/software/gatk-4.4.0.0/gatk'
snpeff_jar='/public/home/huangyj/software/snpEff/snpEff.jar'
threads=20
ref_genome='/public4/home/huangyj/Digitaria/assembly/04gap_filler/Dsan_chr.V2.fa'
###job command
source activate /public/home/huangyj/anaconda3/envs/population 
#---------------------------------input set----------------------------------
#gzvcf=
#---------------------------------command------------------------------------

#java -jar $snpeff_jar build -c /public/home/huangyj/software/snpEff/snpEff.config -gff3 -v YJ2023 
java -jar $snpeff_jar eff -c /public/home/huangyj/software/snpEff/snpEff.config YJ2023 $gzvcf > ${gzvcf/.vcf.gz/}_fded_SNP.eff.vcf -csvStats ${gzvcf/.vcf.gz/}_fded_SNP_positive.csv -stats ${gzvcf/.vcf.gz/}_fded_SNP_positive.html
#java -jar $snpeff_jar eff -c /public/home/huangyj/software/snpEff/snpEff.config YJ2023 ${file_name/vcf/INDEL.fded} > ${file_name%%.*}_fded_INDEL.eff.vcf -csvStats ${file_name%%.*}_fded_INDEL_positive.csv -stats ${file_name%%.*}_fded_INDEL_positive.html

conda deactivate
###job finished reminder
echo "Finish at:"
date -d +20minute +'%Y-%m-%d %H:%M:%S'

