#!/bin/bash
###define PBS arguments

#PBS -N VCF_genetic_filter
#PBS -l nodes=1:ppn=20,walltime=30:00:00:00,mem=300g
#PBS -q fat
#PBS -j oe
#PBS -o log_vcf_genetic_filted

###job starting reminder
echo $USER
echo "Starting job at:"
date -d +20minute +'%Y-%m-%d %H:%M:%S'
set +u -e

###job dir
cd $PBS_O_WORKDIR
###variable
WGS_filter_jar='/public/home/huangyj/software/WGSc-master/excuable/WGS.jar'
threads=20
###job command
source activate /public/home/huangyj/anaconda3/envs/population 
#---------------------------------input set----------------------------------
rawvcf='/public4/home/huangyj/Digitaria/population_downanalysis/vcf_filt/all_ploidy6/Dsan_all_ploidy6.merge.SNP.gz'
input='/public4/home/huangyj/Digitaria/population_downanalysis/vcf_filt/all_ploidy6/Dsan_all_ploidy6.merge.SNP.fded.gz'
file_name=`basename $input`
#---------------------------------command------------------------------------
/public/home/huangyj/software/get_vcf_stat.sh Before_hard_filter $rawvcf
/public/home/huangyj/software/get_vcf_stat.sh After_hard_filter $input

#Segregation test filter
java -jar $WGS_filter_jar --model vcf --type ST --file $input --out ${input%.*}.ST.gz
/public/home/huangyj/software/get_vcf_stat.sh After_Segregate ${input%.*}.ST.gz

#Linkage disequilibrium (LD) filter
java -jar $WGS_filter_jar --model vcf --type LDfilter --windowSize 50 --threshold 0.01 --file ${input%.*}.ST.gz --out ${input%.*}.ST.LD.gz
/public/home/huangyj/software/get_vcf_stat.sh After_LD ${input%.*}.ST.LD.gz

#IBD filter
#divide accessions and obtain the IBD information for each group
#calculate pairwise distribution
#$WGS_filter --model vcf --type IBDfilter --anchorFile anchorSNPs.vcf --minComp 200 --maxIBDDist 0.03 --windowSize 2000 --numThreads 32 --file in.vcf --out outprefix

#Minor allele count filter
vcftools --gzvcf ${input%.*}.ST.LD.gz --recode --recode-INFO-all --maf 0.01 --max-missing 0.7 --stdout > ${input%.*}.ST.LD.MAF.gz
/public/home/huangyj/software/get_vcf_stat.sh After_MAF ${input%.*}.ST.LD.MAF.gz

conda deactivate
###job finished reminder
echo "Finish at:"
date -d +20minute +'%Y-%m-%d %H:%M:%S'

