#!/bin/bash
###define PBS arguments

#PBS -N VCF_stat
#PBS -l nodes=1:ppn=5,walltime=30:00:00:00,mem=300g
#PBS -q fat
#PBS -j oe
#PBS -o log_vcf_stat

###job starting reminder
echo $USER
echo "Starting job at:"
date -d +20minute +'%Y-%m-%d %H:%M:%S'
set +u -e

###job dir
cd $PBS_O_WORKDIR
###variable
threads=5
###job command
source activate /public/home/huangyj/anaconda3/envs/population 
#---------------------------------input set----------------------------------
#gzvcf='/public4/home/huangyj/Digitaria/population_downanalysis/vcf_filt/all_gatk3/Dsan_all.merge.gatk3.vcf.gz'
#file_name=`basename $input`
#pre
#---------------------------------command------------------------------------

/public/home/huangyj/software/get_vcf_stat.sh $pre $gzvcf
#/public/home/huangyj/software/get_vcf_stat.sh After_hard_filter $input

conda deactivate
###job finished reminder
echo "Finish at:"
date -d +20minute +'%Y-%m-%d %H:%M:%S'

