#!/bin/bash
###define PBS arguments
#PBS -N MFG_anno
#PBS -l nodes=1:ppn=20,walltime=2400:00:00
#PBS -q low
#PBS -j oe
#PBS -o log_MFG_annotation

###job starting reminder
echo "Starting job at:"
date
hostname

###job dir
cd $PBS_O_WORKDIR

source activate /public/home/huangyj/anaconda3/envs/r_p
###job command
#fa
#prefix
database='/public4/home/huangyj/Digitaria/related_ref/poaceae_genome/Zmay-B73-5_prot_for_funcanno'

blastp -db $database -query $fa -out ${prefix}_MFG -evalue 1e-10 -outfmt 6 -num_threads 20


###job finished reminder
echo "Finished at:"
date
