#!/bin/bash
###define PBS arguments

#PBS -N Gvcf_db_build
#PBS -l nodes=1:ppn=4,walltime=30:00:00:00,mem=180g
#PBS -q low
#PBS -j oe
#PBS -o log_Gvcf_db_build

###job starting reminder
echo $USER
echo "Starting job at:"
date -d +20minute +'%Y-%m-%d %H:%M:%S'
set -e 
set -u

###job dir
cd $PBS_O_WORKDIR
###variable
gatk_java='/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.262.b10-1.el7.x86_64/jre/bin/java'
build_dict_script="/public/home/huangyj/anaconda3/envs/population/share/picard-2.18.23-0/picard.jar"
gatk4='/public/home/huangyj/software/gatk-4.4.0.0/gatk'
threads=4
ref_genome='/public4/home/huangyj/Digitaria/assembly/04gap_filler/Dsan_chr.V2.fa'
###job command
source activate /public/home/huangyj/anaconda3/envs/population 
#---------------------------------input set----------------------------------
#give gvcf $file
#give chr
mkdir -p /public4/home/huangyj/Digitaria/population/Temp_SNP_joint_caller
gatk_tmpfile=/public4/home/huangyj/Digitaria/population/Temp_SNP_joint_caller

##get fasta idx
if [ ! -s ${ref_genome}.fai ] ; then
samtools faidx ${ref_genome}
fi

gvcf_list=''
for gvcf in `cat $file`
do
    gvcf_list+="-V ${gvcf} "
done

##gvcf combine in one gvcf
mkdir -p all_chr_gvcf_db
$gatk4 --java-options "-Xmx180g" GenomicsDBImport --tmp-dir $gatk_tmpfile $gvcf_list --genomicsdb-workspace-path all_chr_gvcf_db/all_587_database_${chr} -L $chr --batch-size 100  --reader-threads 4

conda deactivate
###job finished reminder
echo "Finish at:"
date -d +20minute +'%Y-%m-%d %H:%M:%S'

