###define PBS arguments
#PBS -N TRASH_with_concensus
#PBS -l nodes=1:ppn=10,walltime=2400:00:00
#PBS -q low
#PBS -j oe
#PBS -o log_TRASH_with_concensus

###job starting reminder
echo "Starting job at:"
date
hostname

###job dir
cd $PBS_O_WORKDIR

#asm .fasta
#concensus TRASH_${i}_155bp_consensus.txt
#pre HDR7
#CEN

###job command
species=${pre}
source activate /public/home/huangyj/anaconda3/envs/trash

echo $species
mkdir -p ${species}_${CEN}_HOR
which Rscript
#sh /public/home/huangyj/software/TRASH-main/TRASH_run.sh $asm --seqt $concensus --simpleplot --horclass `less $concensus | cut -d "," -f 1 | sed -n "2p"`  --par 5 --o ${species}_HOR
sh /public/home/huangyj/software/TRASH_Xie/TRASH_run.sh $asm --seqt $concensus --simpleplot --par 10 --horclass $CEN --o /public4/home/huangyj/Digitaria/genomic_analysis/centromere/${species}_${CEN}_HOR
#sh /public/home/huangyj/software/TRASH-main/TRASH_run.sh $asm --seqt $concensus --simpleplot --par 10 --horclass $CEN --o /public4/home/huangyj/Digitaria/genomic_analysis/centromere/${species}_${CEN}_HOR

###job finished reminder
echo "Finished at:"
date
