#!/bin/bash
###define PBS arguments
#PBS -N rDNA_blast
#PBS -l nodes=1:ppn=10,walltime=30:00:00:00
#PBS -q low
#PBS -j oe
#PBS -o log_rDNA_blast

###job starting reminder
echo "Starting job at:"
date -d +20minute +'%Y-%m-%d %H:%M:%S'
###job dir
cd $PBS_O_WORKDIR

###variable
#asm="/public/home/huangyj/pan_rice/oryrep.ref"
#prefix
rDNA_ref='/public4/home/huangyj/Digitaria/genomic_analysis/rDNA_anno/irgsp_rDNA_rmdup.fasta'
#rDNA_ref='/public4/home/huangyj/Digitaria/genomic_analysis/assessment/Maize_rDNA.fasta'
###job command
source activate /public/home/huangyj/anaconda3/envs/r_p
if [ ! -s ${rDNA_ref%.*}.nhr ] ; then
makeblastdb -in $rDNA_ref -dbtype nucl -parse_seqids -out ${rDNA_ref%.*}
fi
blastn -task megablast -num_threads 10 -db ${rDNA_ref%.*} -query $asm -outfmt 6 -out rDNA_${prefix}_blast.out

if [ ! -s ${rDNA_ref}.fai ] ; then
samtools faidx $rDNA_ref
fi
conda deactivate
#conda deactivate
echo "Finished at:"
date -d +20minute +'%Y-%m-%d %H:%M:%S'

