#!/bin/bash
###define PBS arguments

#PBS -N Subphaser
#PBS -l nodes=1:ppn=5,walltime=30:00:00:00,mem=180g
#PBS -q low
#PBS -j oe
#PBS -o log_subphaser
set +u -e
###job starting reminder

echo "Starting job at:"
date -d +20minute +'%Y-%m-%d %H:%M:%S'
###job dir
cd $PBS_O_WORKDIR
source activate /public/home/huangyj/anaconda3/envs/SubPhaser
prefix=Dsan_V2_subphaser
genome="/public4/home/huangyj/Digitaria/assembly/04gap_filler/Dsan_chr.V2.fa"
#根据基因组内部的同源关系制作config文件
config="/public4/home/huangyj/Digitaria/genomic_analysis/assessment/Dsan_subparser_config"
###job command

subphaser -p 5 -max_memory 180G -i $genome -c $config -pre ${prefix}
conda deactivate
###job finished reminder
echo "Finish at"
date -d +20minute +'%Y-%m-%d %H:%M:%S' 
