#!/bin/bash
#PBS -N busco
#PBS -l nodes=1:ppn=20,walltime=30:00:00:00,mem=180g
#PBS -q low
#PBS -j oe
#PBS -o log_busco

echo "Starting"
date
hostname

#conda activate /public/software/lib/miniconda3/envs/busco_env
source activate /public/home/huangyj/anaconda3/envs/busco-py3.9

cd $PBS_O_WORKDIR
##arguments

#prot="/public4/home/huangyj/tobacco/HDR7_ref/HDR7_prot.v1.0.fasta"
#genome="/public4/home/huangyj/Digitaria/assembly/03polish/Dsan_chr.np2.fa"
dataset="/public/home/huangyj/Database/poales_odb10"
#dataset="/public/software/lib/miniconda3/envs/busco_env/datasets/poales_odb10"
threads=20

##job area
#prefix="Dsan_chr"

busco -f -i $genome -c $threads -o ${prefix}_dna -m geno  -l $dataset --offline -q
busco -f -i $prot -c $threads -o ${prefix}_prot -m prot  -l $dataset --offline -q


conda deactivate

echo "Finished"
date
